name: Output Event Details
on: issues
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            -   name:   Output Issue Event Details
                run:    echo "${{toJson(github.event.issue)}}"